# Site settings
title: "LUTE: Loyola University Technology Ensemble"
short_title: LUTE
#email: your-email@domain.com
description: >
  We are a musical collective creating and performing with new
  technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
facebook_username: LoyolaUniversityTechnologyEnsemble
github_username:  loyola-university-tech-ensemble

current_incapp_win: "https://github.com/loyola-university-tech-ensemble/InC/releases/download/v2.0.0/InC_Winx64.zip"
current_incapp_mac: "https://github.com/loyola-university-tech-ensemble/InC/releases/download/v2.0.0/InCApp_macOS.dmg"

current_projector_win: "https://github.com/loyola-university-tech-ensemble/in-c-score-progress/releases/download/v1.1.0/InCScoreProgress-win32-x64.zip"
current_projector_mac: "https://github.com/loyola-university-tech-ensemble/in-c-score-progress/releases/download/v1.1.0/InCScoreProgress-macos-x64.dmg"
current_projector_lin: "https://github.com/loyola-university-tech-ensemble/in-c-score-progress/releases/download/v1.1.0/InCScoreProgress-linux-x64.zip"

# Build settings
markdown: kramdown

paginate: 6
paginate_path: "/posts/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
